// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	fs "io/fs"

	mock "github.com/stretchr/testify/mock"
)

// Filesystem is an autogenerated mock type for the Filesystem type
type Filesystem struct {
	mock.Mock
}

// Open provides a mock function with given fields: name
func (_m *Filesystem) Open(name string) (fs.File, error) {
	ret := _m.Called(name)

	var r0 fs.File
	if rf, ok := ret.Get(0).(func(string) fs.File); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.File)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
