// Code generated by mockery v2.11.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

// Debug provides a mock function with given fields: msg
func (_m *Logger) Debug(msg interface{}) {
	_m.Called(msg)
}

// Error provides a mock function with given fields: msg
func (_m *Logger) Error(msg interface{}) {
	_m.Called(msg)
}

// Info provides a mock function with given fields: msg
func (_m *Logger) Info(msg interface{}) {
	_m.Called(msg)
}

// NewLogger creates a new instance of Logger. It also registers a cleanup function to assert the mocks expectations.
func NewLogger(t testing.TB) *Logger {
	mock := &Logger{}

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
